### ISSUE TITLE
Blur mod interferes with MineColonies placement

### ISSUE THREAD

**Issue by EddyBuhler** [AshenGaming/potentia-reborn#15]
Trying to place MineColonies buildings apparently counts as having GUI windows open, so the blurring makes placing the building harder.

**Comment by AshenGaming** [comment]
Can you take a screenshot of the issue at hand so I can more easily identify the issue?

**Comment by EddyBuhler** [comment]
Steps to reproduce:

a) craft a supply depot
b) clear a sufficiently large area to place it
c) try to place it (and use the onscreen controls to modify placement, like move up, down etc.)
d) the controls will show up clearly, but the supply depot you're about to place will be blurred and really hard to see, making precise placement a pain

Will attach a screenshot.

**Comment by EddyBuhler** [comment]
![image](https://user-images.githubusercontent.com/17428083/36608045-de92bb1c-18c8-11e8-8405-24bf5cd9a608.png)

**Comment by EddyBuhler** [comment]
Also not sure whether this is a MineColonies thing, but camera look is disabled in this screen, so it's impossible to look around (up or down, for example) to get a better view of where one is placing something.

**Comment by AshenGaming** [comment]
MineColonies is being replaced with Millenaire in version 0.8, so this issue is no longer an issue.
