### ISSUE TITLE
Compressor instabreak

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/potentia-reborn#2]
The block ''Compressor'' from the mod ''Singularities'' will insta break in survival when you hit it once.

**Comment by AshenGaming** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compressor Insta-breaks](https://trello.com/c/3kcOV9Gx/18-compressor-insta-breaks)

**Comment by AshenGaming** [comment]
Fixed in Potentia Reborn 0.4.
