### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by vincentmet** [AshenGaming/potentia-reborn#22]
#### Mods Involved:
- Agricraft

#### Issue type:
- Bug (Crash)

#### Short description:
Ticking block entity crash

#### Expected behaviour:
Block should break normally

#### Actual behaviour:
Getting a CTD, most likely by causing a blockupdate on the block above the agricraft water tank that affects the tileentity, before removing i also broke a transfer pipe(EU2), which worked fine.

#### Steps to reproduce the problem:
Not able to reproduce

#### Additional Information:
https://hastebin.com/raw/acedawowoz

#### Versions:
- Modpack: PotentiaReborn 0.82b

**Comment by AshenGaming** [comment]
Looks like when it rains and the water tank receives that rain it causes this CTD. Will hopefully be fixed in the next AgriCraft update.

**Comment by AshenGaming** [comment]
Fixed in 0.83b.
