### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by vincentmet** [AshenGaming/potentia-reborn#24]
CTD: latest log out of 18
[crash-2018-05-20_11.01.48-client.txt](https://github.com/AshenGaming/potentia-reborn/files/2020191/crash-2018-05-20_11.01.48-client.txt)

**Comment by vincentmet** [comment]
[crash-2018-05-27_12.16.13-client.txt](https://github.com/AshenGaming/potentia-reborn/files/2042518/crash-2018-05-27_12.16.13-client.txt)
[crash-2018-05-27_12.16.20-client.txt](https://github.com/AshenGaming/potentia-reborn/files/2042519/crash-2018-05-27_12.16.20-client.txt)
[crash-2018-05-27_12.40.36-client.txt](https://github.com/AshenGaming/potentia-reborn/files/2042520/crash-2018-05-27_12.40.36-client.txt)

**Comment by AshenGaming** [comment]
Closed. Re-opened as separate issues on bug tracker. #25 #26
