### ISSUE TITLE
Flying millenaires

### ISSUE THREAD

**Issue by vincentmet** [AshenGaming/potentia-reborn#28]
#### Mods Involved:
Millenaire

#### Issue type:
- Bug

#### Short description:
Millewnaires fly to attack you

#### Expected behaviour:
Them to be groundbased

#### Actual behaviour:
flying behind me like the actuallyadditions magnet ring does to items when inv is full

#### Steps to reproduce the problem:
1. Kill a millenaire
2. Fly 

#### Additional Information:
![image](https://user-images.githubusercontent.com/8179290/40585637-b7729c50-61b6-11e8-915a-6a74de232dbb.png)

#### Versions:
Potentia Reborn 0.83b

**Comment by AshenGaming** [comment]
Fixed in the latest millenaire update. Will re-open if the bug still occurs after the next pack update (0.84).
