### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by vincentmet** [AshenGaming/potentia-reborn#29]
#### Mods Involved:
-LittleTiles
-RFTools

#### Issue type:
Config Issue

#### Short description:
Recipe conflict

#### Expected behaviour:
Be able to craft item

#### Actual behaviour:
Getting other item that has the same recipe

#### Steps to reproduce the problem:
Craft either a "Miniature Recipe" from "Little Tiles" or  a "Empty Dimension Dimlet" from RFTools

#### Additional Information:
![image](https://user-images.githubusercontent.com/8179290/40856028-9bb098ae-65d6-11e8-83c6-0c71a55836d7.png)
![image](https://user-images.githubusercontent.com/8179290/40856045-ab4216c6-65d6-11e8-9f9e-3653451a7927.png)

____
#### Versions:
Potentia Reborn 0.84

**Comment by AshenGaming** [comment]
Fixed in 0.85.
