### ISSUE TITLE
Arcane Extractor from crossroads

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/potentia-reborn#5]
If you use a ''Arcane Extractor'' from the mod ''Crossroads'' without a filter and shoot the laser on a arcade reflector it can change to a redstone block

**Comment by AChubbyPinkFluffyFabWhale** [comment]
after some testing around, the first shot can be maximum of 3 blocks then it will turn into a redstone block but if you shoot in the first reflector and then in a another one then this doesn't happen

**Comment by AshenGaming** [comment]
This doesn't seem to be exclusive to just the Arcane Reflector... I'll need to do more digging for this one.

So far the blocks I've found affected are:

- Vanilla Furnace
- Vanilla Enchanting Table
- Arcane Reflector
- Lens Holder (sideways)
- Dispenser
- Dropper
- Observer

**Comment by AshenGaming** [comment]
https://github.com/Da-Technomancer/Crossroads/issues/79
