### ISSUE TITLE
Energy Condenser

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/potentia-reborn#6]
Sometimes when you put a stacked block into the ''Energy condenser'' from the mod ''ProjectE'' it wouldn't work, when you remove it from the stack then it works, if you remove it from the stack while your in the energy condenser it also doesnt work.

**Comment by AshenGaming** [comment]
I need more information on this bug and if you can reproduce it.

**Comment by AChubbyPinkFluffyFabWhale** [comment]
I cant get the stacked issue back to happen,  but it also could be when i open the ''Energy Condenser'' click on a item place it at the dupe location with Right click then it will show me that the item is into that location, Then i close the ''Energy Condenser'' the item isn't there.

1. Open ''energy condenser''
2. Click on a item you wanna dupe
3. Place you're mouse at the ''Dupe location''
4. ''Right click'' The item at the ''Dupe location''

**Comment by AshenGaming** [comment]
Any chance you could record a video of it happening?

**Comment by AChubbyPinkFluffyFabWhale** [comment]
![energy condenser](https://user-images.githubusercontent.com/34548365/35817077-b1edb3e4-0a9c-11e8-82d5-1f72aad49ae3.gif)
