### ISSUE TITLE
Mystical Agriculture and Arcane Extractor

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/potentia-reborn#7]
If you plant a seed from Mystical Agriculture there isn't a way to grow it faster only its own kind of bonemeal called ''Mystical Fertilizer'' regular bonemeal will not work but if you use a Arcane extractor from the mod ''Crossroad'' use a emerald as his lens it will insta grow to its final stage.

**Comment by AshenGaming** [comment]
Requested mod author add a config option https://github.com/Da-Technomancer/Crossroads/issues/75
