### ISSUE TITLE
Everlasting Abilities working strange

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/potentia-reborn#8]
i got some abilities on my character, when i try removing them with a ''Ability bottle'' its working kinda strange as in you select which buff you wanna remove from you character which gives a effect so you can see its selected but when you press the button to remove it then there is a big chance it did remove a total different effect you didnt select

**Comment by AshenGaming** [comment]
Fixed in Potentia Reborn 0.4.
